name: internet_safety_heroes
description: A quiz app to teach kids about internet safety.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/

#  fonts:
#    - family: Comic Sans MS
#      fonts:
##        - asset: assets/fonts/ComicSansMS.ttf
##        - asset: assets/fonts/ComicSansMS-Bold.ttf
#          weight: 700